language: node_js
node_js:
  - "stable"
services:
  - mysql
cache:
  directories:
  - node_modules
install:
  - npm run setup
script:
  - npm test -- --coverage --watchAll=false
  - npm run build
after_success:
  - npm run coveralls